### ISSUE TITLE
At last a good Twig plugin for Vscode: This is awesome!!!

### ISSUE THREAD

**Issue by jimblue** [mblode/vscode-twig-language#1]
THANK YOU!!

**Comment by mblode** [comment]
HAHAHA! Glad you like it! Are you coming from Grav development?

**Comment by jimblue** [comment]
@mblode yep indeed. I saw you too from you theme... (this plugin development make sens now haha)

**Comment by mblode** [comment]
Thanks! Glad it’s useful.
