### ISSUE TITLE
PrettyDiff config ignores editor tab settings

### ISSUE THREAD

**Issue by michaelroper** [mblode/vscode-twig-language#10]
Hey Matt! Is there any way you could add in the option to use tabs for the indentation settings that are passed to PrettyDiff? At the moment, it's defaulting to spaces with no option to change.

It looks like when you pass in the options for the [PrettyDiff config](https://github.com/mblode/vscode-twig-language/blob/master/src/extension.js#L25), you can pass in a key for `inchar`, which would have a value of `' '` for a space (the PrettyDiff default) or `'\t'` for a tab. The tricky part is - if you want to use tabs, the `insize` value should be set back to 1.

Also... instead of having the tab size (and type) set in the `twig-language` settings, could it maybe inherit those from VS Code's `editor.tabSize` and `editor.insertSpaces` settings? This would mean it would also respect what is in my project's `.editorconfig` file ([ref](http://editorconfig.org/)).

Sorry - I'd try a pull request, but I'm not sure of the best way to actually implement it!

(also just noticed #9 - I can see the reason for possibly keeping the language-specific tab-size setting within that scope... but being able to set the tab character would still be good!)

**Comment by mblode** [comment]
Hey @michaelroper, I have just pushed an update to Twig Language 2 with a brand new formatter using Prettydiff 3 which brings about some major bug fixes. I have finally fixed this issue with the newest update to Twig Language. Simply set your "twig-language: tabSize" to 0 and it will default to your "editor: tabSIze".  Sorry about the slow development speeds and sub-par communication but hopefully these updates have fixed some of your other problems.

**Comment by michaelroper** [comment]
Thanks for the follow-up Matt. Funnily enough, I ended up disabling the formatting part of the extension, and using the [UniBeautify](https://unibeautify.com) extension, which I think was using PrettyDiff 3 for Twig as well. I'll give it another shot anyway, cheers!

**Comment by mblode** [comment]
This has finally been resolved with the most recent update to the extensions (0.9.0). You can now choose the indentStyle in the config.

Thank you so much for your patience!

**Comment by dzpt** [comment]
@mblode after choosing indent style to space.
default is space 2, but after format, it always convert to space 4??!

**Comment by mblode** [comment]
@dzpt You need to set the indent style to "space" and the tab size to 2. Then also restart VSCode. Please let me know if this works for you

**Comment by mblode** [comment]
0.10.0 respects the document’s tab size and indentation style. Added tests for tabs, spaces and settings changes.
