### ISSUE TITLE
Issues formatting block shortcuts

### ISSUE THREAD

**Issue by italodr** [mblode/vscode-twig-language#15]
Hey Matt! Is it possible to add support to [Block shortcuts](https://twig.symfony.com/doc/2.x/tags/extends.html#block-shortcuts)?
Right now is indenting the code below as if it were inside the `{% block %}` tag.

<img width="448" alt="block-shortcut-indentation" src="https://user-images.githubusercontent.com/2691320/39626311-a6ae0048-4fa1-11e8-9ee2-59f07661874c.png">

**Comment by wolfmoritz** [comment]
+1 Same issue here

**Comment by mblode** [comment]
I noticed this issue too and I'll raise it with the developer of the Pretty Diff formatter 👍

**Comment by mblode** [comment]
This has been fixed in the latest update 👍

**Comment by mblode** [comment]
Fixed Twig block shorthand formatting in 0.10.0 and added regression tests.
