### ISSUE TITLE
Respect editorconfig indentation settings

### ISSUE THREAD

**Issue by PhilippeSchraepen** [mblode/vscode-twig-language#16]
Right now, we have to manually update the number of spaces in the VS Code configuration file. It would be better if it would respect the .editorconfig file / plugin.

**Comment by mblode** [comment]
Hey @PhilippeSchraepen, I have finally fixed this issue with the newest update to Twig Language. Simply set your "twig-language: tabSize" to `0` and it will default to your "editor: tabSIze".

**Comment by mblode** [comment]
0.10.0 respects the document’s tab size and indentation style. Added tests for tabs, spaces and settings changes.
