### ISSUE TITLE
add option to enable/disable function

### ISSUE THREAD

**Issue by jimblue** [mblode/vscode-twig-language#2]
Is it possible to add options to enable/disable snippets, syntax highlighting, hover, and formatting?

**Comment by mblode** [comment]
Yeah that was a feature I was definitely considering. So are you thinking they are all on by default and it gives you the option to toggle them off? E.g. Twig Language Formatting: false, Twig Language hover: false, Twig Language snippets: false, Twig Language syntax: false in the user settings?

**Comment by jimblue** [comment]
Yep that would be the more convenient!

**Comment by mblode** [comment]
I have just pushed an update to allow you to enable or disable formatting along with the hover feature. You can also configure some options that effect twig formatting.

**Comment by mblode** [comment]
You can disable formatting with "twig-language.formatting": false. 0.10.0 applies changes without restarting.
