### ISSUE TITLE
formatting script inside custom block went wrong

### ISSUE THREAD

**Issue by aron19951209** [mblode/vscode-twig-language#25]
#### Before Formatting
<img width="584" alt="螢幕快照 2019-04-11 下午6 26 12" src="https://user-images.githubusercontent.com/33840671/55950350-4cc79780-5c87-11e9-93e2-33aff64c77b5.png">

#### After Formatting
<img width="570" alt="螢幕快照 2019-04-11 下午6 27 24" src="https://user-images.githubusercontent.com/33840671/55950404-7680be80-5c87-11e9-9e2e-4dc284307991.png">

**Comment by mblode** [comment]
Sorry about this major bug! I've pushed a fix for this issue but please let me know if you're still running into any issues 👍

**Comment by aron19951209** [comment]
@mblode You fix it so fast. I found other issues and I would new issue later. Thank you for your contribution. The extension is so useful for me. :0

**Comment by mblode** [comment]
0.10.0 preserves Twig-generated JavaScript and custom script block contents. Added regression coverage.
