### ISSUE TITLE
Formatting json incorrectly

### ISSUE THREAD

**Issue by aron19951209** [mblode/vscode-twig-language#28]
### incorrect indentation ☹️
<img width="569" alt="螢幕快照 2019-04-13 上午1 52 42" src="https://user-images.githubusercontent.com/33840671/56056521-ff365200-5d8e-11e9-9252-a578f64f47d2.png">

### expected indentation 😊
<img width="569" alt="螢幕快照 2019-04-13 上午1 55 17" src="https://user-images.githubusercontent.com/33840671/56056588-3278e100-5d8f-11e9-8b07-7e9237063ba7.png">

**Comment by mblode** [comment]
This has been fixed in the latest update 👍

**Comment by mblode** [comment]
0.10.0 preserves JSON data-script contents and includes a regression test.
