### ISSUE TITLE
I cannot get the formatter to respect the 2 spaces indent setting

### ISSUE THREAD

**Issue by sveggiani** [mblode/vscode-twig-language#29]
No matter what, when the document is formatted a 4 spaces indentation is applied.

**Comment by mblode** [comment]
Thanks @sveggiani for bringing this to my attention! I've just pushed a fix and indentation should work properly now 👍

**Comment by dzpt** [comment]
@mblode i still have this error.

**Comment by FrederickEngelhardt** [comment]
same.

**Comment by mblode** [comment]
0.10.0 respects the document’s tab size and indentation style. Added tests for tabs, spaces and settings changes.
