### ISSUE TITLE
Html autoComplete Not Working

### ISSUE THREAD

**Issue by zerp300** [mblode/vscode-twig-language#37]
hello , i have a strange bug with the extension , everytime i open visual studio code (1.36.1) i need to disable and enable the extension to make html autocompletion to work.
Can i have a fix for it. thanks

**Comment by gavinhewitt** [comment]
Having the same issue.

**Comment by sarim** [comment]
same issue. Any fix?

**Comment by tsawitzki** [comment]
Still experiencing this bug in March 2023 with the latest release

**Comment by mblode** [comment]
0.10.0 keeps native HTML IntelliSense. Twig Language 2 now also bundles HTML completion if you prefer a separate Twig mode.
