### ISSUE TITLE
HTML Autocomplete Not Working

### ISSUE THREAD

**Issue by bgarrant** [mblode/vscode-twig-language#4]
Can you add the setting so the HTML Autocomplete/Intellesense works when using .twig or .html? I thought there was a user setting for it, but it appears it is in the extension. Just start typing `<div` and you should get the Intellesense pop up. It is not working when twig syntax is used. If you look at the Twig Pack extension it does work in that one somehow. Not sure that is best example but you get that idea.

**Comment by bgarrant** [comment]
All HTML functions including Autocomplete/Intellesense should work within Twig as well. That is how PHPStorm and Atom works.

**Comment by bgarrant** [comment]
Somehow this old extension kind of had it working https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-twig-pack

**Comment by bgarrant** [comment]
https://github.com/Microsoft/vscode/issues/670

**Comment by mblode** [comment]
I will release a working version later tonight! Get excited!!

**Comment by mblode** [comment]
Just to clarify, do you also want formatting of twig to work in .html files?

**Comment by bgarrant** [comment]
We need the HTML Autocomplete to work along with Twig. I think the way that older extension did it is made use of the .html extension so that Twig and HTML Autocomplete would both work.

**Comment by bgarrant** [comment]
So if you type `<div` you should see the Autocomplete/Intellesense wrench icon in the suggestions. All I get is the word based ABC one

**Comment by bgarrant** [comment]
Great work on all this by the way Matt

**Comment by bgarrant** [comment]
I think VSC has to believe that .html and .twig both are HTML syntax. Then it can be tricked so Autocomplete works. Somehow they did it with https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-twig-pack. If you open a .html or .twig file it says syntax HTML in corner

**Comment by bgarrant** [comment]
Maybe that is how they had it working

**Comment by bgarrant** [comment]
The formatting, coloring, everything should work same in .html and .twig ideally. Hopefully that helps.

**Comment by Arnauw** [comment]
It's 2021 and I have the same issue, even after adding every twig extensions I found

**Comment by iamfrankeu** [comment]
@Arnauw I'm also still looking forward for a fix...

**Comment by buba71** [comment]
Me too...

**Comment by nhurst-knight** [comment]
Had the same issue and found this on details for Twig Language 2 

> This extension does not have HTML Intellisense. If you need HTML Intellisense (which can be quite useful), please download my other Twig Language extension: https://github.com/mblode/vscode-twig-language.

Add the below into your settings and it works a treat 

```
"files.associations": {
    "*.html": "twig"
},
"emmet.includeLanguages": {
    "twig": "html"
},
```

**Comment by buba71** [comment]
It's work for me. Great!! Thanks @nhurst-knight

**Comment by Marvelxy** [comment]
Works for me too.

**Comment by AmineGroot** [comment]
I have been looking for this solution for too long , Thanks A Lot !

**Comment by LuigiVampa21** [comment]
Thank you !!!

**Comment by tsawitzki** [comment]
Still experiencing this to be not working with the latest version in March 2023.
Set interpreter to "HTML (Twig" -> All autocompleting for HTML tags gone

**Comment by mblode** [comment]
0.10.0 keeps native HTML IntelliSense. Twig Language 2 now also bundles HTML completion if you prefer a separate Twig mode.
