### ISSUE TITLE
twig are consider HTML5

### ISSUE THREAD

**Issue by jimblue** [mblode/vscode-twig-language#5]
One strange thing with the new update Twig file know are read as HTML5 files.

<img width="301" alt="screen shot 2017-11-25 at 17 33 56" src="https://user-images.githubusercontent.com/10623367/33232447-d8230b3c-d206-11e7-910a-15d1c6160fd4.png">

Is it possible to revert that?

**Comment by mblode** [comment]
I have changed this on order to provide the Twig files with HTML5 intellisence, autocomplete, Emmet and hover that is all built into VSCode. Personally I think this provides a better experience but maybe I can make option to configure this.

**Comment by jimblue** [comment]
Sure XP is better! Just this HTML5 icon is disturbing, maybe picky ^^

**Comment by mblode** [comment]
Haha I feel you! I'm just as picky... Hence this extension. I'll see what I can do

**Comment by jimblue** [comment]
Thanks to try, don't want to loose my last eye! 😝

**Comment by vieko** [comment]
Another picky prick here :) Adding the following to your folder / workspace settings does the trick without messing any of the advantages provided by the extension:

`"vsicons.associations.files": [
      { "icon": "twig", "extensions": ["twig", "html"], "format": "svg" }
    ],`

**Comment by mblode** [comment]
G'day mates,
I have created a new extension to fix the issues that I (and all of you) were having with file associations, issues with commenting and also the most important issue with the icon in the sidebar. 

https://marketplace.visualstudio.com/items?itemName=mblode.twig-language-2
https://github.com/mblode/vscode-twig-language-2

Simply add these lines to your VSCode settings to get emmet and HTML Intellisense working and also to associate HTML files as twig syntax.
```
"files.associations": {
    "*.html": "twig"
},
"emmet.includeLanguages": {
    "twig": "html"
},
```

**Comment by jimblue** [comment]
Thanks for the fix 👍

**Comment by mblode** [comment]
HTML mode is retained for compatibility. Twig Language 2 uses a separate Twig mode; both now share the same formatter and grammar.
