### ISSUE TITLE
formatting - linebreaks in html tags (on attributes) will be removed

### ISSUE THREAD

**Issue by amkdev** [mblode/vscode-twig-language#58]
I don't know - maybe there is an option to prevent this ...

but it really get's me nuts that on formatting twig html, all manual inserted line breaks on a html tag (a lot of attributes with long values) will be removed and I got an ultra long single line of html.

is it possible to change this behaviour?

**Comment by mblode** [comment]
0.10.0 preserves existing multiline attributes and supports the attribute-wrapping settings.
