### ISSUE TITLE
There is no formatter for 'twig' files installed.

### ISSUE THREAD

**Issue by cjwest** [mblode/vscode-twig-language#59]
I'm confused. I have installed and enabled this extension. I restarted VSCode, but when I try to format my twig code I get

There is no formatter for 'twig' files installed.

![Screen Shot 2021-08-23 at 11 21 35 AM](https://user-images.githubusercontent.com/284440/130497496-4cd29d81-09a3-40e5-978f-a7a57a2307f6.png)

What am I missing?

**Comment by cjwest** [comment]
Looks like there might have been a conflict with this extension:
https://marketplace.visualstudio.com/items?itemName=whatwedo.twig

I disabled it, and now Twig formatting is working with alt-shift-F

**Comment by mblode** [comment]
Twig Language still uses HTML mode in 0.10.0. For a dedicated Twig language mode, use Twig Language 2; both share the formatter.
