### ISSUE TITLE
Code changed to gray after latest update

### ISSUE THREAD

**Issue by dhprins** [mblode/vscode-twig-language#63]
Hi, after your last update(v0.9.3) my code inside vcode turned to gray. Can you fix this in the next update? Thanks!

**Comment by Bachellereau** [comment]
Hi, same here my code inside VScode turned to gray since last update :/

**Comment by jeffaglenn** [comment]
Same

**Comment by florianbouvot** [comment]
+1

**Comment by maximeDore** [comment]
+1 but also the snippets are not working either.

**Comment by SandersImagetools** [comment]
+1

**Comment by dialogticket** [comment]
+1
All syntax highlighting for HTML no longer works.

**Comment by DerMudder** [comment]
+1
All syntax highlighting for HTML no longer works.

**Comment by ianshea** [comment]
+1 Syntax highlighting doesn't work anymore

**Comment by danielsitek** [comment]
+1 same

**Comment by jwrudzin** [comment]
Same here, downgrading to 0.9.2 fixed the issue.

**Comment by mblode** [comment]
My sincerest apologies! I've reverted the latest changes. This should be fixed in 0.9.4

**Comment by mblode** [comment]
0.10.0 includes grammar fixes, but I couldn’t confirm this exact case. Please share a small example if the gray highlighting remains.
