### ISSUE TITLE
Tab size

### ISSUE THREAD

**Issue by ntomka** [mblode/vscode-twig-language#9]
Great extension!

Can you add tabSize option in settings? It formats every line with 2 spaces identation, but I prefer 4 spaces. I can't find option anywhere to change this.

**Comment by mblode** [comment]
Ok

**Comment by ntomka** [comment]
Wow, that was a fast Christmas gift! Nice! :beers:
Thank you!

**Comment by mblode** [comment]
0.10.0 respects the document’s tab size and indentation style. Added tests for tabs, spaces and settings changes.
